name : Bug
description: 在使用时遇到了问题 I encountered a problem while using
title: 你发现的问题 The problem you found
labels: ["bug","To be viewed","open"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您发现问题，请您起一个能清晰概括问题的标题。 Thank you for finding the problem. Please give a title that can clearly summarize the problem.

        >[!CAUTION]
        > 请不要在一个issue中提出多个问题，一个issue只对应一个问题。
        > 
        > 请不要在issue里提出无关此issue的的问题。
        > 
        > 请不要在issue里包含非法字符！
        > 
        > Do not raise multiple questions in one issue. One issue should only be for one question.
        > 
        > Please do not raise questions unrelated to this issue in the issue.
        >
        > Please do not include illegal characters in your issue!

        > [!TIP]
        > 如果您不知道如何有效、精准地表述，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
        > 
        > If you don't know how to express yourself effectively and accurately, we recommend that you read[<How To Ask Questions The Smart Way>](http://www.catb.org/~esr/faqs/smart-questions.html)
  - type: checkboxes
    id: checkbox
    attributes:
      label: 检查清单 Checklist
      description: 在开始反馈这个问题之前，请先检查： Before you start reporting this issue, please check
      options:
        - label: 我已将更新到最新版，并已经在[最新issues](https://github.com/WRD1145/PerHome/issues)中查看 I have updated to the latest version and have checked it in the [latest issues](https://github.com/WRD1145/PerHome/issues)
          required: true
        - label: 我已经仔细阅读过选项里的内容，并且知道这个选项不用勾选。 I have read the options carefully and know that this option does not need to be checked.
          required: false
        - label: 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。 I understand and agree that this is only for reporting issues with the program (other issues not related to the program itself should be raised in the Discussion section).
          required: true
  - type: markdown
    id: exception
    attributes:
      value: |
        ## Bug信息 Bug Information

        描述您遇到的 Bug。您可以附上截图、录屏等材料，便于开发者追踪问题。 Describe the bug you encountered. You can attach screenshots, screen recordings, etc. to help developers track the problem. **

        > [!note]
        > 上传附件时**请优先使用 GitHub 的附件系统上传附件**，将需要上传的附件粘贴或拖动到撰写区域即可上传。多个文件可打包为 zip 格式后上传。
        > 
        >When uploading attachments, **please use GitHub's attachment system first**. Paste or drag the attachments you want to upload into the compose area to upload. Multiple files can be packaged into zip format and uploaded.

  - type: input
    id: excepted
    attributes:
      label: 期望的行为 Desired behavior
      description: 详细的描述你期望发生的行为，突出与目前（可能不正确的）行为的不同。 Describe in detail the behavior you expect to occur, highlighting any differences from the current (possibly incorrect) behavior.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 实际结果 Actual Results
      description: 实际发生的行为。 The behavior that actually occurred.
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: 重现步骤 Steps to reproduce
      description: |
        详细描述要怎么操作才能再次触发这个 Bug。 Describe in detail what needs to be done to trigger the bug again.
      placeholder: |
        1. 首先…… First......
        2. 然后…… Then......
        3. ……
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 版本 version
      description: 您当前使用的版本号。The version number you are currently using.
      placeholder: 如：2.0.1 For example:2.0.1
    validations:
      required: true
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步 Final Step
      description: 回顾您的回答 Review your answers
      options:
        - label: 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。 I think the above description is detailed enough for developers to understand the functionality you want. If my issue is not filled in according to the above requirements, it may be closed unconditionally.
          required: true
