name: enhancement 新功能
description: Propose a new feature. 提出一项新的功能。
title: （将此栏【替换】为你的标题） (Replace this column with your title)
labels: ["enhancement", "To be viewed", "open"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing your idea. Please give this feature a title that clearly summarizes your idea so that developers can understand it.
        感谢您贡献您的想法。请起一个能够清晰概括此功能的标题，便于开发者了解您的想法。
        
        > [!WARNING]
        > 如果您想要提出 **多项功能**，请为每一个功能开一个单独的 issue。
        > 
        > 由于开发者时间精力有限，提交的功能请求可能需要比较久的时间才能实现。
        > 
        > If you would like to propose **multiple features**, please open a separate issue for each one.
        > 
        > Due to the limited time and energy of developers, submitted feature requests may take a long time to implement.

        >[!CAUTION]
        > 请不要在一个issue中提出多个问题，一个issue只对应一个问题。
        > 
        > 请不要在issue里提出无关此issue的的问题。
        > 
        > 请不要在issue里包含非法字符！
        > 
        > Do not raise multiple questions in one issue. One issue should only be for one question.
        > 
        > Please do not raise questions unrelated to this issue in the issue.
        >
        > Please do not include illegal characters in your issue!

        > [!TIP]
        > 如果您不知道如何有效、精准地表述，我们建议您先阅读[《提问的智慧》](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
        > 
        > If you don't know how to express yourself effectively and accurately, we recommend that you read[<How To Ask Questions The Smart Way>](http://www.catb.org/~esr/faqs/smart-questions.html)
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单 Checklist
      description: 在开始反馈这个问题之前，请先检查： Before you start reporting this issue, please check
      options:
        - label: 我已将更新到最新版，并已经在[最新issues](https://github.com/lihansen136/ClassIsland-Timed-Alert-Floater/issues?q=is%3Aissue%20label%3A%E6%96%B0%E5%8A%9F%E8%83%BD)查看过。 I have updated to the latest version and have checked the [latest issues](https://github.com/lihansen136/ClassIsland-Timed-Alert-Floater/issues?q=is%3Aissue%20label%3A%E6%96%B0%E5%8A%9F%E8%83%BD).
          required: true
        - label: 我已经仔细阅读过选项里的内容，并且知道这个选项不用勾选。 I have read the options carefully and know that this option does not need to be checked.
          required: false
        - label: 我已知晓由于开发者时间精力有限，我提交的功能请求可能需要比较久的时间才能实现。 I understand that due to the limited time and energy of developers, the feature request I submitted may take a long time to implement.
          required: true
  - type: markdown
    attributes: 
      value: |
        > [!note]
        > 上传附件时**请优先使用 GitHub 的附件系统上传附件**，将需要上传的附件粘贴或拖动到撰写区域即可上传。多个文件可打包为 zip 格式后上传。
        > 
        >When uploading attachments, **please use GitHub's attachment system first**. Paste or drag the attachments you want to upload into the compose area to upload. Multiple files can be packaged into zip format and uploaded.
  - type: textarea
    id: back
    attributes:
      label: 背景与动机 Background and Motivation
      description: 为什么你需要这个功能？ Why do you need this feature?
    validations:
      required: true
  - type: textarea
    id: req
    attributes:
      label: 想要实现或优化的功能 Functions that you want to implement or optimize
      description: 详细地描述一下你想要的功能，描述的越具体，采纳的可能性越高。 Describe the features you want in detail. The more specific you are, the more likely it is to be adopted.
    validations:
      required: true
  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步 Final Step
      description: 回顾您的回答 Review your answers
      options:
        - label: 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。 I think the above description is detailed enough for developers to understand the functionality you want. If my issue is not filled in according to the above requirements, it may be closed unconditionally.
          required: true
